### DISCUSSION TITLE
匹配规则后，只能覆写 targetAccount 和 methodAccount 字段吗？是否可以再覆写 “Naration” 字段？

### DISCUSSION THREAD

**Discussion by TTtrace** [deb-sig/double-entry-generator#134] [Q&A]
比如有以下记录：

```beancount
2024-06-14 * "宋家小厨房" "收款方备注:二维码收款"
	method: "工商银行储蓄卡(0183)"
	payTime: "2024-06-14 07:48:52 +0800 CST"
	source: "微信支付"
	status: "已转账"
	txType: "扫二维码付款"
	type: "支出"
	Expenses:EatDrink:Meals 5.00 CNY
	Assets:ICBC:Debit:0183 -5.00 CNY
```

规则：

```yaml
    - peer: 宋家小厨房
      targetAccount: Expenses:EatDrink:Meals
    - method: 工商银行储蓄卡(0183)
      fullMatch: true
      methodAccount: Assets:ICBC:Debit:0183
```

如果我想在匹配 `peer: 宋家小厨房` 后不仅覆写 `targetAccount` ，还进一步覆写 ` naration` 字段变成：

```beancount
2024-06-14 * "宋家小厨房" "北门口煎饼果子"
	method: "工商银行储蓄卡(0183)"
	payTime: "2024-06-14 07:48:52 +0800 CST"
	source: "微信支付"
	status: "已转账"
	txType: "扫二维码付款"
	type: "支出"
	Expenses:EatDrink:Meals 5.00 CNY
	Assets:ICBC:Debit:0183 -5.00 CNY
```

是否可以呢？

**Comment by gaocegege** [comment]
Hi 这个需求场景是什么

**Comment by Triple-Z** [comment]
您指的 `naration` 在 `double-entry-generator` 中称为 `item` ，且 `item` 也可作为一个独立的匹配条件。本项目主要目标是将导出的账单尽可能一致地转换为 beancount 格式。如果有覆写描述等需求，建议用添加后置脚本等方式来完成。

**Comment by Triple-Z** [comment]
这个需要一个 if-then 的逻辑，而当前的 rules 中所有条件都是且的匹配关系，`then` 仅针对 `targetAccount` ，并没有针对 `item` 赋值的功能。

如果想设计该需求，配置文件可能要改成这个样子：

```yaml
    - peer: 宋家小厨房
      targetAccount: Expenses:EatDrink:Meals
      output:
        item: 北门口煎饼果子
```
