### ISSUE TITLE
config file for ICBC not work

### ISSUE THREAD

**Issue by saccohuo** [deb-sig/double-entry-generator#119]
**Describe the bug**
I am using ICBC bill translator, the result has no account name in the last two lines in each transaction.
I delete the config.yaml, and get the same result. It seems that the translator do not recognize the config file.
OS version: Windows 10
generator version: 2023/9/10 master branch, golang version

config.yaml: 
```
defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCashAccount: Assets:DebitCard:工商银行
defaultCurrency: CNY
title: 测试
icbc:
  rules:
    - peer: 财付通-,支付宝
      sep: ","
      ignore: true
```

translate shell command:
```
./double-entry-generator translate --append  --config ../config/icbc/config.yaml --provider icbc --output ../tmp/icbc-output.bean ../tmp/icbc_record.csv
```

result:
```
2023-01-03 * "财付通-满座儿万科店 深圳市财付通支付科技有限公司"
	balances: "53635.87"
	currency: "人民币"
	peerAccount: "深圳市财付通支付科技有限公司"
	source: "中国工商银行"
	txType: "消费"
	type: "支出"
	 22.80 
	 -22.80 

2023-01-03 * "财付通-满座儿万科店 深圳市财付通支付科技有限公司"
	balances: "53613.54"
	currency: "人民币"
	peerAccount: "深圳市财付通支付科技有限公司"
	source: "中国工商银行"
	txType: "消费"
	type: "支出"
	 22.33 
	 -22.33 
```
