### ISSUE TITLE
[feature] Support time condition in rules 

### ISSUE THREAD

**Issue by Triple-Z** [deb-sig/double-entry-generator#31]
Example rule:

```yaml
- peer: 餐厅
  time: 11:00-15:00
  targetAccount: Expenses:Food:Meal:Lunch
```

Explanation: 
- **If** the transaction's peer contains `餐厅`,
  - **And** transaction's time is between `11:00` and `15:00`,
- **Then** `targetAccount` is `Expenses:Food:Meal:Lunch`.
