### ISSUE TITLE
Issue with Alipay refund transactions with txType as "收入"

### ISSUE THREAD

**Issue by wych42** [deb-sig/double-entry-generator#82]
在处理支付宝账单的时候，遇到「收/支」一列标记为「收入」的退款交易。如图：
<img width="595" alt="image" src="https://user-images.githubusercontent.com/9361073/215124384-e0831480-bb6e-4178-a7e9-f657ddfa38a1.png">

转换后，预期这笔交易的plusAccount是methodAccount，即对应的银行卡账户。实际上银行卡账户是minusAccount。导致支出交易和退款交易都在银行卡账户上记录了minus金额。

有问题的example csv:
[example-alipay-records.csv](https://github.com/deb-sig/double-entry-generator/files/10520463/example-alipay-records.csv)

对应配置:
```
defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCurrency: CNY
title: 测试
alipay:
  rules:
    - peer: 神州租车
      targetAccount: Expenses:Rental:Car
    
    - method: 招商银行(9876)
      fullMatch: true
      methodAccount: Assets:Bank:CN:CMB-9876:Savings
```

输出结果
```
option "title" "测试"
option "operating_currency" "CNY"

1970-01-01 open Assets:Bank:CN:CMB-9876:Savings
1970-01-01 open Assets:FIXME
1970-01-01 open Expenses:FIXME
1970-01-01 open Expenses:Rental:Car

2023-01-21 * "神州租车" "神州租车产品"
	category: "交通出行"
	merchantId: "yyy   "
	method: "招商银行(9876)"
	orderId: "xxx"
	payTime: "2023-01-21 09:31:32 +0800 CST"
	source: "支付宝"
	status: "交易关闭"
	txType: "支出"
	Expenses:Rental:Car 278.98 CNY
	Assets:Bank:CN:CMB-9876:Savings -278.98 CNY

2023-01-21 * "神州租车" "退款-神州租车产品"
	category: "退款"
	merchantId: "yyy   "
	method: "招商银行(9876)"
	orderId: "xxx1371263536677"
	payTime: "2023-01-21 09:35:43 +0800 CST"
	source: "支付宝"
	status: "退款成功"
	txType: "收入"
	Expenses:Rental:Car 278.98 CNY
	Assets:Bank:CN:CMB-9876:Savings -278.98 CNY
```
